name: "Dokku and Docker Registry Login"
description: "GitHub Action to handle authentication for both Dokku and Docker registries, allowing seamless login to multiple Docker registries and setting up Dokku on remote servers. Supports Docker-in-Docker and automatically configures credentials for deployments."
author: "Matias Alvarez Sabate"
inputs:
  registrys:
    description: "matrix of registries, pass using toJson(matrix.registrys)"
    required: true
    type: object
  USER_SSH:
    description: "User to connect to server by ssh. "
    required: true
    type: string
  IP_SERVER:
    description: "IP of server"
    required: true
    type: string
  PRIVATE_KEY_SERVER_DEPLOY:
    description: "Private SSH key for server"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.PRIVATE_KEY_SERVER_DEPLOY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan ${{ inputs.IP_SERVER }} >> ~/.ssh/known_hosts

    - name: Login to Docker registries
      run: |
        ssh -t ${{ inputs.USER_SSH }}@${{ inputs.IP_SERVER }} <<EOF
          set -e
          if [ "${{ inputs.registrys.login_to_dokku }}" = true ]; then
            dokku registry:login ${{ inputs.registrys.registry}} ${{ inputs.registrys.user}} ${{ inputs.registrys.password }}
          fi
          if [ "${{ inputs.registrys.login_to_docker }}" = true ]; then
            echo ${{ inputs.registrys.password }} | sudo docker login ${{ inputs.registrys.registry}} -u ${{ inputs.registrys.user}} --password-stdin
          fi
        EOF
