name: "Dokku and Docker Registry Login"
description: "GitHub Action to handle authentication for both Dokku and Docker registries, allowing seamless login to multiple Docker registries and setting up Dokku on remote servers. Supports Docker-in-Docker and automatically configures credentials for deployments."
author: "Matias Alvarez Sabate"
inputs:
  registrys:
    description: "Array of registries"
    required: true
    type: string
  user_ssh:
    description: "User to connect to server by ssh."
    required: true
    type: string
  ip_server:
    description: "IP of server"
    required: true
    type: string
  private_key_server_deploy:
    description: "Private SSH key for server"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ inputs.private_key_server_deploy }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan ${{ inputs.ip_server }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Login to Docker registries
      run: |
        ssh -t ${{ inputs.user_ssh }}@${{ inputs.ip_server }} <<EOF
          set -e
          echo '${{ inputs.registrys }}' | jq -c '.[]' | while read -r i; do
            REGISTRY=$(echo "$i" | jq -r '.registry // empty')
            USERNAME=$(echo "$i" | jq -r '.username // empty')
            PASSWORD=$(echo "$i" | jq -r '.password // empty')
            LOGIN_TO_DOKKU=$(echo "$i" | jq -r '.login_to_dokku // empty')
            LOGIN_TO_DOCKER=$(echo "$i" | jq -r '.login_to_docker // empty')

            if [ -z "$REGISTRY" ] || [ -z "$USERNAME" ] || [ -z "$PASSWORD" ] || [ -z "$LOGIN_TO_DOKKU" ] || [ -z "$LOGIN_TO_DOCKER" ]; then
              echo "Error: Missing required fields in the JSON."
              exit 1
            fi

            # Ejecutar el login en Dokku si está habilitado
            if [ "$LOGIN_TO_DOKKU" = "true" ]; then
              dokku registry:login "$REGISTRY" "$USERNAME" "$PASSWORD"
            fi
            
            # Ejecutar el login en Docker si está habilitado
            if [ "$LOGIN_TO_DOCKER" = "true" ]; then
              echo "$PASSWORD" | sudo docker login "$REGISTRY" -u "$USERNAME" --password-stdin
            fi
          done
        EOF
      shell: bash
